/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InternalAxiosRequestConfig } from "axios";

/**
* Interface with which a configuration object can be configured.
*/
export interface ConfigurationOptions {
    /**
    * The API key to use for authentication. This can also be set as an
    * environment variable FIREBLOCKS_API_KEY
    */
    apiKey?: string
    /**
    * The secret key to use for authentication. This can also be set as an
    * environment variable FIREBLOCKS_SECRET_KEY
    */
    secretKey?: string;
    /**
    * The base path for the server against which to make requests. This can
    * also be set as an environment variable FIREBLOCKS_BASE_PATH.
    */
    basePath?: BasePath | string;
    /**
    * Additional options to configure the SDK
    */
    additionalOptions?: AdditionalOptions;
}

export interface AdditionalOptions {
    /** Base options for axios calls */
    baseOptions?: Partial<InternalAxiosRequestConfig>;

    /** Whether to remove platform from User-Agent header */
    isAnonymousPlatform?: boolean;

    /** Additional product identifier to be prepended to the User-Agent header */
    userAgent?: string;
}

export enum BasePath {
    Sandbox = 'https://sandbox-api.fireblocks.io/v1',
    US = 'https://api.fireblocks.io/v1',
    EU = 'https://eu-api.fireblocks.io/v1',
    EU2 = 'https://eu2-api.fireblocks.io/v1',
}
