/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AssetTypeResponse {
    'id': string;
    'name': string;
    'type': AssetTypeResponse.TypeEnum;
    'contractAddress'?: string;
    'nativeAsset'?: string;
    'decimals'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AssetTypeResponse.TypeEnum"
        },
        {
            "name": "contractAddress",
            "baseName": "contractAddress",
            "type": "string"
        },
        {
            "name": "nativeAsset",
            "baseName": "nativeAsset",
            "type": "string"
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AssetTypeResponse.attributeTypeMap;
    }
}

export namespace AssetTypeResponse {
    export enum TypeEnum {
        AlgoAsset = <any> 'ALGO_ASSET',
        BaseAsset = <any> 'BASE_ASSET',
        Bep20 = <any> 'BEP20',
        Compound = <any> 'COMPOUND',
        Erc20 = <any> 'ERC20',
        Fiat = <any> 'FIAT',
        SolAsset = <any> 'SOL_ASSET',
        TronTrc20 = <any> 'TRON_TRC20',
        XlmAsset = <any> 'XLM_ASSET',
        XdbAsset = <any> 'XDB_ASSET'
    }
}
