/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthorizationGroups {
    'th'?: number;
    'users'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "th",
            "baseName": "th",
            "type": "number"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return AuthorizationGroups.attributeTypeMap;
    }
}

export namespace AuthorizationGroups {
    export enum UsersEnum {
        PendingAuthorization = <any> 'PENDING_AUTHORIZATION',
        Approved = <any> 'APPROVED',
        Rejected = <any> 'REJECTED',
        Na = <any> 'NA'
    }
}
