/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExchangeAsset } from './exchangeAsset';
import { ExchangeTradingAccount } from './exchangeTradingAccount';
import { ExchangeType } from './exchangeType';

export class ExchangeAccount {
    'id'?: string;
    'type'?: ExchangeType;
    /**
    * Display name of the exchange account
    */
    'name'?: string;
    'status'?: string;
    'assets'?: Array<ExchangeAsset>;
    'tradingAccounts'?: Array<ExchangeTradingAccount>;
    /**
    * True if the account is a subaccount in an exchange
    */
    'isSubaccount'?: boolean;
    /**
    * if the account is a sub-account, the ID of the main account
    */
    'mainAccountId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ExchangeType"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<ExchangeAsset>"
        },
        {
            "name": "tradingAccounts",
            "baseName": "tradingAccounts",
            "type": "Array<ExchangeTradingAccount>"
        },
        {
            "name": "isSubaccount",
            "baseName": "isSubaccount",
            "type": "boolean"
        },
        {
            "name": "mainAccountId",
            "baseName": "mainAccountId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExchangeAccount.attributeTypeMap;
    }
}

export namespace ExchangeAccount {
}
