/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FeeInfo {
    'networkFee'?: string;
    'serviceFee'?: string;
    'gasPrice'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "networkFee",
            "baseName": "networkFee",
            "type": "string"
        },
        {
            "name": "serviceFee",
            "baseName": "serviceFee",
            "type": "string"
        },
        {
            "name": "gasPrice",
            "baseName": "gasPrice",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FeeInfo.attributeTypeMap;
    }
}

