/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.5
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RewardInfo } from './rewardInfo';
import { TransferPeerPathResponse } from './transferPeerPathResponse';

export class NetworkRecord {
    'source'?: TransferPeerPathResponse;
    'destination'?: TransferPeerPathResponse;
    'txHash'?: string;
    'networkFee'?: string;
    'assetId'?: string;
    /**
    * The net amount of the transaction, after fee deduction
    */
    'netAmount'?: string;
    'isDropped'?: boolean;
    'type'?: string;
    'destinationAddress'?: string;
    'sourceAddress'?: string;
    'amountUSD'?: string;
    'index'?: number;
    'rewardInfo'?: RewardInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "TransferPeerPathResponse"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "TransferPeerPathResponse"
        },
        {
            "name": "txHash",
            "baseName": "txHash",
            "type": "string"
        },
        {
            "name": "networkFee",
            "baseName": "networkFee",
            "type": "string"
        },
        {
            "name": "assetId",
            "baseName": "assetId",
            "type": "string"
        },
        {
            "name": "netAmount",
            "baseName": "netAmount",
            "type": "string"
        },
        {
            "name": "isDropped",
            "baseName": "isDropped",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "destinationAddress",
            "baseName": "destinationAddress",
            "type": "string"
        },
        {
            "name": "sourceAddress",
            "baseName": "sourceAddress",
            "type": "string"
        },
        {
            "name": "amountUSD",
            "baseName": "amountUSD",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number"
        },
        {
            "name": "rewardInfo",
            "baseName": "rewardInfo",
            "type": "RewardInfo"
        }    ];

    static getAttributeTypeMap() {
        return NetworkRecord.attributeTypeMap;
    }
}

