/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionRequest } from './transactionRequest';

export class RemoveCollateralRequestBody {
    'transactionRequest'?: TransactionRequest;
    /**
    * optional
    */
    'isDstCollateral'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transactionRequest",
            "baseName": "transactionRequest",
            "type": "TransactionRequest"
        },
        {
            "name": "isDstCollateral",
            "baseName": "isDstCollateral",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return RemoveCollateralRequestBody.attributeTypeMap;
    }
}

