/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TravelRuleUpdateVASPDetails {
    /**
    * The decentralized identifier of the VASP
    */
    'did': string;
    /**
    * The PII DID key of the VASP
    */
    'piiDidkey': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "did",
            "baseName": "did",
            "type": "string"
        },
        {
            "name": "piiDidkey",
            "baseName": "pii_didkey",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TravelRuleUpdateVASPDetails.attributeTypeMap;
    }
}

