name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking change'
  - title: '🚀 Feature'
    labels:
      - 'feature'
  - title: '🔧 Fix'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
  default: patch
template: |
  $BODY
autolabeler:
  - label: 'breaking change'
    title:
      - '/\(major\)/'
  - label: 'feature'
    title:
      - '/\(minor\)/'
  - label: 'fix'
    title:
      - '/\(patch\)/'
  - label: 'chore'
    title:
      - '/^$/' 

