name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'major'
  - title: '🚀 Feature'
    labels:
      - 'minor'
  - title: '🔧 Fix'
    labels:
      - 'patch'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $BODY
autolabeler:
  - label: 'major'
    title:
      - '/major/i'
  - label: 'minor'
    title:
      - '/minor/i'
  - label: 'patch'
    title:
      - '/patch/i'
