            export * from './auditLogsApi';
            import { AuditLogsApi } from './auditLogsApi';
            export * from './contractsApi';
            import { ContractsApi } from './contractsApi';
            export * from './exchangeAccountsApi';
            import { ExchangeAccountsApi } from './exchangeAccountsApi';
            export * from './externalWalletsApi';
            import { ExternalWalletsApi } from './externalWalletsApi';
            export * from './fiatAccountsApi';
            import { FiatAccountsApi } from './fiatAccountsApi';
            export * from './gasStationsApi';
            import { GasStationsApi } from './gasStationsApi';
            export * from './internalWalletsApi';
            import { InternalWalletsApi } from './internalWalletsApi';
            export * from './networkConnectionApi';
            import { NetworkConnectionApi } from './networkConnectionApi';
            export * from './networkConnectionsApi';
            import { NetworkConnectionsApi } from './networkConnectionsApi';
            export * from './offExchangesApi';
            import { OffExchangesApi } from './offExchangesApi';
            export * from './paymentsApi';
            import { PaymentsApi } from './paymentsApi';
            export * from './supportedAssetsApi';
            import { SupportedAssetsApi } from './supportedAssetsApi';
            export * from './transactionsApi';
            import { TransactionsApi } from './transactionsApi';
            export * from './transferTicketsApi';
            import { TransferTicketsApi } from './transferTicketsApi';
            export * from './usersApi';
            import { UsersApi } from './usersApi';
            export * from './vaultsApi';
            import { VaultsApi } from './vaultsApi';
            export * from './web3ConnectionsBetaApi';
            import { Web3ConnectionsBetaApi } from './web3ConnectionsBetaApi';
            export * from './webhooksApi';
            import { WebhooksApi } from './webhooksApi';

    export { RequestFile } from '../model/models';
    export const APIS = [AuditLogsApi, ContractsApi, ExchangeAccountsApi, ExternalWalletsApi, FiatAccountsApi, GasStationsApi, InternalWalletsApi, NetworkConnectionApi, NetworkConnectionsApi, OffExchangesApi, PaymentsApi, SupportedAssetsApi, TransactionsApi, TransferTicketsApi, UsersApi, VaultsApi, Web3ConnectionsBetaApi, WebhooksApi];
