/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { convertToFireblocksResponse } from "../response/fireblocksResponse";
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
import { assertParamExistsAndNotEmpty } from '../utils/validation_utils';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { ErrorSchema } from '../models';
/**
 * ResetDeviceApi - axios parameter creator
 * @export
 */
export const ResetDeviceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Resets mobile device for given console user, that user will need to do mobile onboarding again.
         * @summary Resets device
         * @param {string} id The ID of the console user
         * @param {string} [idempotencyKey] A unique identifier for the request. If the request is sent multiple times with the same idempotency key, the server will return the same response as the first request. The idempotency key is valid for 24 hours.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetDevice: async (id: string, idempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            assertParamExistsAndNotEmpty('resetDevice', 'id', id)
            const localVarPath = `/management/users/{id}/reset_device`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ResetDeviceApi - functional programming interface
 * @export
 */
export const ResetDeviceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ResetDeviceApiAxiosParamCreator(configuration)
    return {
        /**
         * Resets mobile device for given console user, that user will need to do mobile onboarding again.
         * @summary Resets device
         * @param {string} id The ID of the console user
         * @param {string} [idempotencyKey] A unique identifier for the request. If the request is sent multiple times with the same idempotency key, the server will return the same response as the first request. The idempotency key is valid for 24 hours.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetDevice(id: string, idempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetDevice(id, idempotencyKey, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ResetDeviceApi.resetDevice']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * ResetDeviceApi - factory interface
 * @export
 */
export const ResetDeviceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ResetDeviceApiFp(configuration)
    return {
        /**
         * Resets mobile device for given console user, that user will need to do mobile onboarding again.
         * @summary Resets device
         * @param {ResetDeviceApiResetDeviceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetDevice(requestParameters: ResetDeviceApiResetDeviceRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.resetDevice(requestParameters.id, requestParameters.idempotencyKey, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for resetDevice operation in ResetDeviceApi.
 * @export
 * @interface ResetDeviceApiResetDeviceRequest
 */
export interface ResetDeviceApiResetDeviceRequest {
    /**
     * The ID of the console user
     * @type {string}
     * @memberof ResetDeviceApiResetDevice
     */
    readonly id: string

    /**
     * A unique identifier for the request. If the request is sent multiple times with the same idempotency key, the server will return the same response as the first request. The idempotency key is valid for 24 hours.
     * @type {string}
     * @memberof ResetDeviceApiResetDevice
     */
    readonly idempotencyKey?: string
}

/**
 * ResetDeviceApi - object-oriented interface
 * @export
 * @class ResetDeviceApi
 * @extends {BaseAPI}
 */
export class ResetDeviceApi extends BaseAPI {
    /**
     * Resets mobile device for given console user, that user will need to do mobile onboarding again.
     * @summary Resets device
     * @param {ResetDeviceApiResetDeviceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResetDeviceApi
     */
    public resetDevice(requestParameters: ResetDeviceApiResetDeviceRequest) {
        return ResetDeviceApiFp(this.configuration).resetDevice(requestParameters.id, requestParameters.idempotencyKey).then((request) => request(this.axios, this.basePath)).then(convertToFireblocksResponse);
    }
}

