name: Auto Reply on New Issues
on:
  pull_request:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Choose random reply message
        id: choose_message
        run: |
          reply_messages=(
            "Thank you for raising this! We will review it shortly."
            "We appreciate your contribution. Our team will investigate this shortly."
            "Your request has been noted. We'll get back to you soon."
            "Thanks for submitting this. We'll review it and provide updates soon."
            "Thank you for letting us know about this. We'll investigate and get back to you soon."
            "Acknowledged. We'll review and respond soon."
            "Thanks for bringing this to our attention. We'll review and provide updates soon."
            "We've received your request. Thanks for your patience."
            "Noted. Expect updates shortly."
            "Your request is important to us. We will look into it shortly."
          )
          random_index=$((RANDOM % ${#reply_messages[@]}))
          echo "::set-output name=message::${reply_messages[$random_index]}"

      - name: Reply to issue using GitHub CLI
        if: (!contains(fromJSON('["YoavBZ", "asaf"]'), github.event.pull_request.user.login))
        run: |
          gh pr comment ${{ github.event.number }} --body "${{ steps.choose_message.outputs.message }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
