name: Create Pull Request

on:
  push:
    branches:
      - 'fireblocks-api-spec/generated/*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          npm install
          npm i -g auto-changelog
      - name: Bump version and add changelog
        run: |
          initialTag=v1.1.1
          tag="${initialTag//[v]/}"
          echo $tag
          git remote update
          git fetch
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Github Actions"
          npm --no-git-tag-version --allow-same-version version $tag
          auto-changelog --hide-credit -l 0 -b 3
          git add .
          git commit -m "release $tag"
          git push
  create-pull-request:
    needs: bump-version
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create pull request
        run: |
          gh pr create \
            --title "${{ github.event.commits[0].message }}" \
            --body "This PR was automatically generated." \
            --base master \
            --head ${{ github.ref }} \
            --reviewer asafs932,zoharsf,YoavBZ
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
