/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Current status of the allowlist entry.   - `ACTIVE` — Entry is approved and usable.   - `PENDING_PROVIDER_COOLDOWN` — Entry was recently added or modified and is in the provider-enforced cooldown window before becoming active.   - `PENDING_PROVIDER_REVIEW` — Entry is awaiting provider-side review.   - `PENDING_APPROVAL` — Entry is awaiting customer/admin approval on the Fireblocks side.   - `REJECTED` — Entry was rejected at submission time and will not become active.   - `REMOVED` — Entry was deactivated after previously being active. May still appear in results for audit purposes. 
 * @export
 * @enum {string}
 */

export const AllowlistEntryStatus = {
    Active: 'ACTIVE',
    PendingProviderCooldown: 'PENDING_PROVIDER_COOLDOWN',
    PendingProviderReview: 'PENDING_PROVIDER_REVIEW',
    PendingApproval: 'PENDING_APPROVAL',
    Rejected: 'REJECTED',
    Removed: 'REMOVED'
} as const;

export type AllowlistEntryStatus = typeof AllowlistEntryStatus[keyof typeof AllowlistEntryStatus];



