/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AssetMetadata } from './asset-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { AssetOnchain } from './asset-onchain';

/**
 * 
 * @export
 * @interface AssetResponse
 */
export interface AssetResponse {
    /**
     * 
     * @type {string}
     * @memberof AssetResponse
     */
    'legacyId': string;
    /**
     * 
     * @type {string}
     * @memberof AssetResponse
     */
    'assetClass': AssetResponseAssetClassEnum;
    /**
     * 
     * @type {AssetOnchain}
     * @memberof AssetResponse
     */
    'onchain': AssetOnchain;
    /**
     * 
     * @type {AssetMetadata}
     * @memberof AssetResponse
     */
    'metadata': AssetMetadata;
}

export const AssetResponseAssetClassEnum = {
    Native: 'NATIVE',
    Ft: 'FT',
    Nft: 'NFT',
    Sft: 'SFT'
} as const;

export type AssetResponseAssetClassEnum = typeof AssetResponseAssetClassEnum[keyof typeof AssetResponseAssetClassEnum];


