/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Canton domain a transaction belongs to. Singular, and it matches the prefix of the `type` / `responseType` values in the same domain character for character.
 * @export
 * @enum {string}
 */

export const CantonDomainEnum = {
    Onboarding: 'ONBOARDING',
    Allocation: 'ALLOCATION',
    Transfer: 'TRANSFER'
} as const;

export type CantonDomainEnum = typeof CantonDomainEnum[keyof typeof CantonDomainEnum];



