/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AllowListPayload } from './allow-list-payload';

/**
 * 
 * @export
 * @interface CantonCallAllowListRemove
 */
export interface CantonCallAllowListRemove {
    /**
     * Which call to make. Selects the shape of `payload`.
     * @type {string}
     * @memberof CantonCallAllowListRemove
     */
    'type': CantonCallAllowListRemoveTypeEnum;
    /**
     * 
     * @type {AllowListPayload}
     * @memberof CantonCallAllowListRemove
     */
    'payload': AllowListPayload;
}

export const CantonCallAllowListRemoveTypeEnum = {
    DtccAllowListRemove: 'DTCC_ALLOW_LIST_REMOVE'
} as const;

export type CantonCallAllowListRemoveTypeEnum = typeof CantonCallAllowListRemoveTypeEnum[keyof typeof CantonCallAllowListRemoveTypeEnum];


