/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbiFunction } from './abi-function';
// May contain unused imports in some cases
// @ts-ignore
import { ContractAttributes } from './contract-attributes';
// May contain unused imports in some cases
// @ts-ignore
import { ContractDoc } from './contract-doc';

/**
 * 
 * @export
 * @interface ContractUploadRequest
 */
export interface ContractUploadRequest {
    /**
     * The name of the contract template
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'name': string;
    /**
     * A short description of the contract template
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'description': string;
    /**
     * The compiled artifact of this smart contract. Used for deployment of this contract template
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'bytecode': string;
    /**
     * The type of the contract template
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'type': ContractUploadRequestTypeEnum;
    /**
     * The abi of the contract template. Necessary for displaying and for after deployment encoding
     * @type {Array<AbiFunction>}
     * @memberof ContractUploadRequest
     */
    'abi': Array<AbiFunction>;
    /**
     * A full description of the contract template. May contain   to break the lines
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'longDescription'?: string;
    /**
     * The source code of the contract. Optional.
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'sourcecode'?: string;
    /**
     * A `natspec` compliant documentation json. Can be retrieved from the output json after compilation
     * @type {ContractDoc}
     * @memberof ContractUploadRequest
     */
    'docs'?: ContractDoc;
    /**
     * The attributes related to this contract template. It will be displayed in the tokenization page
     * @type {ContractAttributes}
     * @memberof ContractUploadRequest
     */
    'attributes'?: ContractAttributes;
    /**
     * The protocol that the template will be used for
     * @type {string}
     * @memberof ContractUploadRequest
     */
    'protocol'?: ContractUploadRequestProtocolEnum;
}

export const ContractUploadRequestTypeEnum = {
    FungibleToken: 'FUNGIBLE_TOKEN',
    NonFungibleToken: 'NON_FUNGIBLE_TOKEN',
    NonToken: 'NON_TOKEN',
    TokenExtension: 'TOKEN_EXTENSION',
    TokenUtility: 'TOKEN_UTILITY'
} as const;

export type ContractUploadRequestTypeEnum = typeof ContractUploadRequestTypeEnum[keyof typeof ContractUploadRequestTypeEnum];
export const ContractUploadRequestProtocolEnum = {
    Eth: 'ETH',
    Sol: 'SOL'
} as const;

export type ContractUploadRequestProtocolEnum = typeof ContractUploadRequestProtocolEnum[keyof typeof ContractUploadRequestProtocolEnum];


