/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuditorData } from './auditor-data';

/**
 * 
 * @export
 * @interface ContractAttributes
 */
export interface ContractAttributes {
    /**
     * 
     * @type {Array<string>}
     * @memberof ContractAttributes
     */
    'useCases': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContractAttributes
     */
    'standards': Array<string>;
    /**
     * 
     * @type {AuditorData}
     * @memberof ContractAttributes
     */
    'auditor': AuditorData;
}

