/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbiFunction } from './abi-function';
// May contain unused imports in some cases
// @ts-ignore
import { Parameter } from './parameter';
// May contain unused imports in some cases
// @ts-ignore
import { SOLAccount } from './solaccount';
// May contain unused imports in some cases
// @ts-ignore
import { SolParameter } from './sol-parameter';
// May contain unused imports in some cases
// @ts-ignore
import { SolanaInstruction } from './solana-instruction';

/**
 * @type ContractAbiResponseDtoAbiInner
 * @export
 */
export type ContractAbiResponseDtoAbiInner = AbiFunction | SolanaInstruction;


