/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Cosigner } from './cosigner';

/**
 * 
 * @export
 * @interface CosignersPaginatedResponse
 */
export interface CosignersPaginatedResponse {
    /**
     * The data of the current page
     * @type {Array<Cosigner>}
     * @memberof CosignersPaginatedResponse
     */
    'data': Array<Cosigner>;
    /**
     * The ID of the next page
     * @type {string}
     * @memberof CosignersPaginatedResponse
     */
    'next'?: string | null;
}

