/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { VersionSummary } from './version-summary';

/**
 * 
 * @export
 * @interface Cosigner
 */
export interface Cosigner {
    /**
     * Whether the cosigner is archived
     * @type {boolean}
     * @memberof Cosigner
     */
    'archived': boolean;
    /**
     * The unique identifier of the cosigner
     * @type {string}
     * @memberof Cosigner
     */
    'id': string;
    /**
     * The name of the cosigner
     * @type {string}
     * @memberof Cosigner
     */
    'name'?: string;
    /**
     * The type of the cosigner
     * @type {string}
     * @memberof Cosigner
     */
    'type'?: CosignerTypeEnum;
    /**
     * 
     * @type {VersionSummary}
     * @memberof Cosigner
     */
    'version'?: VersionSummary;
}

export const CosignerTypeEnum = {
    Sandbox: 'SANDBOX',
    Sgx: 'SGX',
    GcpConfspace: 'GCP-CONFSPACE',
    AwsNitro: 'AWS-NITRO',
    Plain: 'PLAIN'
} as const;

export type CosignerTypeEnum = typeof CosignerTypeEnum[keyof typeof CosignerTypeEnum];


