/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NetworkIdRoutingPolicyValue } from './network-id-routing-policy-value';

/**
 * 
 * @export
 * @interface CreateNetworkIdRequest
 */
export interface CreateNetworkIdRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNetworkIdRequest
     */
    'name': string;
    /**
     * 
     * @type {{ [key: string]: NetworkIdRoutingPolicyValue; }}
     * @memberof CreateNetworkIdRequest
     */
    'routingPolicy'?: { [key: string]: NetworkIdRoutingPolicyValue; };
}

