/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateNcwConnectionRequest
 */
export interface CreateNcwConnectionRequest {
    /**
     * The ID of the Non-Custodial Wallet to connect to the dApp.
     * @type {string}
     * @memberof CreateNcwConnectionRequest
     */
    'ncwId': string;
    /**
     * The NCW account ID to connect to the dApp.
     * @type {number}
     * @memberof CreateNcwConnectionRequest
     */
    'ncwAccountId': number;
    /**
     * The default fee level. Valid values are `MEDIUM` and `HIGH`.
     * @type {string}
     * @memberof CreateNcwConnectionRequest
     */
    'feeLevel': CreateNcwConnectionRequestFeeLevelEnum;
    /**
     * The WalletConnect uri provided by the dapp.
     * @type {string}
     * @memberof CreateNcwConnectionRequest
     */
    'uri': string;
    /**
     * The IDs of the blockchain networks used in the Web3 connection (Currently required in V1 connections only).
     * @type {Array<string>}
     * @memberof CreateNcwConnectionRequest
     */
    'chainIds'?: Array<string>;
}

export const CreateNcwConnectionRequestFeeLevelEnum = {
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;

export type CreateNcwConnectionRequestFeeLevelEnum = typeof CreateNcwConnectionRequestFeeLevelEnum[keyof typeof CreateNcwConnectionRequestFeeLevelEnum];


