/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAddressResponse
 */
export interface CreateAddressResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAddressResponse
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressResponse
     */
    'legacyAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressResponse
     */
    'enterpriseAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAddressResponse
     */
    'tag'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateAddressResponse
     */
    'bip44AddressIndex'?: number;
}

