/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateMultichainTokenRequestCreateParams } from './create-multichain-token-request-create-params';

/**
 * 
 * @export
 * @interface CreateMultichainTokenRequest
 */
export interface CreateMultichainTokenRequest {
    /**
     * The id of the vault account that initiated the request to issue the token
     * @type {string}
     * @memberof CreateMultichainTokenRequest
     */
    'vaultAccountId': string;
    /**
     * 
     * @type {CreateMultichainTokenRequestCreateParams}
     * @memberof CreateMultichainTokenRequest
     */
    'createParams': CreateMultichainTokenRequestCreateParams;
    /**
     * The base asset identifiers of the blockchains (legacyId) to calculate deterministic addresses
     * @type {Array<string>}
     * @memberof CreateMultichainTokenRequest
     */
    'chains': Array<string>;
    /**
     * The salt to calculate the deterministic address. Must be a number between 0 and 2^256 -1, for it to fit in the bytes32 parameter.
     * @type {string}
     * @memberof CreateMultichainTokenRequest
     */
    'salt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMultichainTokenRequest
     */
    'displayName'?: string;
    /**
     * Indicates whether the token should be created in a gasless manner, utilizing the ERC-2771 standard. When set to true, the transaction will be relayed by a designated relayer. The workspace must be configured to use Fireblocks gasless relay.
     * @type {boolean}
     * @memberof CreateMultichainTokenRequest
     */
    'useGasless'?: boolean;
    /**
     * Max fee amount for the write function transaction. interchangeable with the \'feeLevel\' field
     * @type {string}
     * @memberof CreateMultichainTokenRequest
     */
    'fee'?: string;
    /**
     * Fee level for the write function transaction. interchangeable with the \'fee\' field
     * @type {string}
     * @memberof CreateMultichainTokenRequest
     */
    'feeLevel'?: CreateMultichainTokenRequestFeeLevelEnum;
}

export const CreateMultichainTokenRequestFeeLevelEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;

export type CreateMultichainTokenRequestFeeLevelEnum = typeof CreateMultichainTokenRequestFeeLevelEnum[keyof typeof CreateMultichainTokenRequestFeeLevelEnum];


