/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DirectAccess
 */
export interface DirectAccess {
    /**
     * Indicates this uses direct provider access
     * @type {string}
     * @memberof DirectAccess
     */
    'type': DirectAccessTypeEnum;
    /**
     * The ID of the provider
     * @type {string}
     * @memberof DirectAccess
     */
    'providerId': string;
}

export const DirectAccessTypeEnum = {
    Provider: 'PROVIDER'
} as const;

export type DirectAccessTypeEnum = typeof DirectAccessTypeEnum[keyof typeof DirectAccessTypeEnum];


