/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DvnConfigWithConfirmations
 */
export interface DvnConfigWithConfirmations {
    /**
     * Array of required DVN Ethereum addresses that sign ULN messages.
     * @type {Array<string>}
     * @memberof DvnConfigWithConfirmations
     */
    'dvnAddresses': Array<string>;
    /**
     * Minimum number of DVN signatures required (M-of-N).
     * @type {number}
     * @memberof DvnConfigWithConfirmations
     */
    'optionalThreshold': number;
    /**
     * Number of block confirmations required
     * @type {number}
     * @memberof DvnConfigWithConfirmations
     */
    'confirmations': number;
    /**
     * Array of optional DVN Ethereum addresses that sign ULN messages.
     * @type {Array<string>}
     * @memberof DvnConfigWithConfirmations
     */
    'optionalDVNAddresses'?: Array<string>;
}

