/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmbeddedWalletDevice
 */
export interface EmbeddedWalletDevice {
    /**
     * deviceId
     * @type {string}
     * @memberof EmbeddedWalletDevice
     */
    'deviceId': string;
    /**
     * enabled
     * @type {boolean}
     * @memberof EmbeddedWalletDevice
     */
    'enabled': boolean;
    /**
     * physicalDeviceId
     * @type {string}
     * @memberof EmbeddedWalletDevice
     */
    'physicalDeviceId': string;
}

