/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Generic fee breakdown for other blockchains
 * @export
 * @interface FeeBreakdownOneOf1
 */
export interface FeeBreakdownOneOf1 {
    /**
     * Base fee component
     * @type {string}
     * @memberof FeeBreakdownOneOf1
     */
    'baseFee'?: string;
    /**
     * Priority fee component
     * @type {string}
     * @memberof FeeBreakdownOneOf1
     */
    'priorityFee'?: string;
    /**
     * Total fee amount
     * @type {string}
     * @memberof FeeBreakdownOneOf1
     */
    'totalFee'?: string;
}

