/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FiatTransfer
 */
export interface FiatTransfer {
    /**
     * The amount of the fiat transfer.
     * @type {string}
     * @memberof FiatTransfer
     */
    'amount': string;
    /**
     * 
     * @type {string}
     * @memberof FiatTransfer
     */
    'type'?: FiatTransferTypeEnum;
    /**
     * The reference ID for the fiat transfer.
     * @type {string}
     * @memberof FiatTransfer
     */
    'referenceId'?: string;
}

export const FiatTransferTypeEnum = {
    Fiat: 'FIAT'
} as const;

export type FiatTransferTypeEnum = typeof FiatTransferTypeEnum[keyof typeof FiatTransferTypeEnum];


