/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FixedFee
 */
export interface FixedFee {
    /**
     * 
     * @type {string}
     * @memberof FixedFee
     */
    'amountType': FixedFeeAmountTypeEnum;
    /**
     * The fixed amount of the fee
     * @type {string}
     * @memberof FixedFee
     */
    'amount': string;
}

export const FixedFeeAmountTypeEnum = {
    Fixed: 'FIXED'
} as const;

export type FixedFeeAmountTypeEnum = typeof FixedFeeAmountTypeEnum[keyof typeof FixedFeeAmountTypeEnum];


