/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FpsHkAddress
 */
export interface FpsHkAddress {
    /**
     * Full legal name of the recipient
     * @type {string}
     * @memberof FpsHkAddress
     */
    'recipientLegalName'?: string;
    /**
     * Recipient bank account number
     * @type {string}
     * @memberof FpsHkAddress
     */
    'accountNumber'?: string;
    /**
     * Hong Kong bank code
     * @type {string}
     * @memberof FpsHkAddress
     */
    'bankCode'?: string;
    /**
     * Recipient phone number in E.164 format
     * @type {string}
     * @memberof FpsHkAddress
     */
    'phone'?: string;
    /**
     * Recipient email address
     * @type {string}
     * @memberof FpsHkAddress
     */
    'email'?: string;
    /**
     * Hong Kong FPS identifier
     * @type {string}
     * @memberof FpsHkAddress
     */
    'fpsId'?: string;
}

