/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAuditLogsResponseDTO
 */
export interface GetAuditLogsResponseDTO {
    /**
     * 
     * @type {Array<object>}
     * @memberof GetAuditLogsResponseDTO
     */
    'data'?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof GetAuditLogsResponseDTO
     */
    'total'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAuditLogsResponseDTO
     */
    'cursor'?: string | null;
}

