/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Paging } from './paging';
// May contain unused imports in some cases
// @ts-ignore
import { TokenResponse } from './token-response';

/**
 * 
 * @export
 * @interface GetNFTsResponse
 */
export interface GetNFTsResponse {
    /**
     * 
     * @type {Paging}
     * @memberof GetNFTsResponse
     */
    'paging'?: Paging;
    /**
     * 
     * @type {Array<TokenResponse>}
     * @memberof GetNFTsResponse
     */
    'data'?: Array<TokenResponse>;
}

