/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LegacyAmountAggregationTimePeriodMethod } from './legacy-amount-aggregation-time-period-method';

/**
 * Defines the method by which the Policy Engine calculates accumulation. It uses the Initiator, Source, and Destination to calculate accumulation toward the value under Minimum, for the time under Time Period. 
 * @export
 * @interface LegacyPolicyRuleAmountAggregation
 */
export interface LegacyPolicyRuleAmountAggregation {
    /**
     * 
     * @type {LegacyAmountAggregationTimePeriodMethod}
     * @memberof LegacyPolicyRuleAmountAggregation
     */
    'operators'?: LegacyAmountAggregationTimePeriodMethod;
    /**
     * 
     * @type {LegacyAmountAggregationTimePeriodMethod}
     * @memberof LegacyPolicyRuleAmountAggregation
     */
    'srcTransferPeers'?: LegacyAmountAggregationTimePeriodMethod;
    /**
     * 
     * @type {LegacyAmountAggregationTimePeriodMethod}
     * @memberof LegacyPolicyRuleAmountAggregation
     */
    'dstTransferPeers'?: LegacyAmountAggregationTimePeriodMethod;
}



