/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GleifData } from './gleif-data';
// May contain unused imports in some cases
// @ts-ignore
import { LeiStatus } from './lei-status';
// May contain unused imports in some cases
// @ts-ignore
import { TravelRuleProvider } from './travel-rule-provider';

/**
 * Legal entity registration record
 * @export
 * @interface LegalEntityRegistration
 */
export interface LegalEntityRegistration {
    /**
     * Unique registration identifier
     * @type {string}
     * @memberof LegalEntityRegistration
     */
    'id': string;
    /**
     * Legal Entity Identifier (LEI) code
     * @type {string}
     * @memberof LegalEntityRegistration
     */
    'lei': string;
    /**
     * 
     * @type {LeiStatus}
     * @memberof LegalEntityRegistration
     */
    'status': LeiStatus;
    /**
     * Whether this is the default legal entity for the workspace
     * @type {boolean}
     * @memberof LegalEntityRegistration
     */
    'isDefault': boolean;
    /**
     * Travel rule providers configured for this registration
     * @type {Array<TravelRuleProvider>}
     * @memberof LegalEntityRegistration
     */
    'travelRuleProviders': Array<TravelRuleProvider>;
    /**
     * Creation timestamp in milliseconds since epoch
     * @type {string}
     * @memberof LegalEntityRegistration
     */
    'createdAt': string;
    /**
     * Last update timestamp in milliseconds since epoch
     * @type {string}
     * @memberof LegalEntityRegistration
     */
    'updatedAt': string;
    /**
     * Contact email for travel rule communications
     * @type {string}
     * @memberof LegalEntityRegistration
     */
    'travelRuleContactEmail'?: string;
    /**
     * 
     * @type {GleifData}
     * @memberof LegalEntityRegistration
     */
    'gleifData'?: GleifData;
}



