/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApprovalApiKey } from './approval-api-key';

/**
 * The approval API keys registered for the API user.
 * @export
 * @interface ListApprovalApiKeysResponse
 */
export interface ListApprovalApiKeysResponse {
    /**
     * The registered approval API keys.
     * @type {Array<ApprovalApiKey>}
     * @memberof ListApprovalApiKeysResponse
     */
    'data': Array<ApprovalApiKey>;
    /**
     * Cursor for the next page of results. Pass it back as the `pageCursor` query param to fetch the next page. Empty or absent when this is the last page.
     * @type {string}
     * @memberof ListApprovalApiKeysResponse
     */
    'next'?: string;
}

