/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FeeLevel } from './fee-level';

/**
 * 
 * @export
 * @interface MergeStakeAccountsRequest
 */
export interface MergeStakeAccountsRequest {
    /**
     * Id of the source position to merge from
     * @type {string}
     * @memberof MergeStakeAccountsRequest
     */
    'sourceId': string;
    /**
     * Id of the destination position to merge into
     * @type {string}
     * @memberof MergeStakeAccountsRequest
     */
    'destinationId': string;
    /**
     * Represents the fee for a transaction, which can be specified as a percentage value. Only one of fee/feeLevel is required.
     * @type {string}
     * @memberof MergeStakeAccountsRequest
     */
    'fee'?: string;
    /**
     * 
     * @type {FeeLevel}
     * @memberof MergeStakeAccountsRequest
     */
    'feeLevel'?: FeeLevel;
    /**
     * The note to associate with the merge transaction.
     * @type {string}
     * @memberof MergeStakeAccountsRequest
     */
    'txNote'?: string;
}



