/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Players } from './players';

/**
 * 
 * @export
 * @interface MpcKey
 */
export interface MpcKey {
    /**
     * 
     * @type {string}
     * @memberof MpcKey
     */
    'keyId': string;
    /**
     * The user id that owns the key
     * @type {string}
     * @memberof MpcKey
     */
    'userId': string;
    /**
     * The algorithm of the key
     * @type {number}
     * @memberof MpcKey
     */
    'algorithm': number;
    /**
     * The players that are associated with the key
     * @type {Array<Players>}
     * @memberof MpcKey
     */
    'players': Array<Players>;
    /**
     * The last index used on this key
     * @type {number}
     * @memberof MpcKey
     */
    'lastPreprocessedIndex'?: number;
}

