/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NetworkFee
 */
export interface NetworkFee {
    /**
     * 
     * @type {string}
     * @memberof NetworkFee
     */
    'feePerByte'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkFee
     */
    'gasPrice'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkFee
     */
    'networkFee'?: string;
    /**
     * (optional) Base Fee according to EIP-1559 (ETH assets)
     * @type {string}
     * @memberof NetworkFee
     */
    'baseFee'?: string;
    /**
     * (optional) Priority Fee according to EIP-1559 (ETH assets)
     * @type {string}
     * @memberof NetworkFee
     */
    'priorityFee'?: string;
}

