/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The status of the Notification
 * @export
 * @enum {string}
 */

export const NotificationStatus = {
    Completed: 'COMPLETED',
    Failed: 'FAILED',
    InProgress: 'IN_PROGRESS'
} as const;

export type NotificationStatus = typeof NotificationStatus[keyof typeof NotificationStatus];



