/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OnchainTransferEvent
 */
export interface OnchainTransferEvent {
    /**
     * Unique identifier for the transfer event
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'id': string;
    /**
     * Hash of the transaction containing this transfer
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'transactionHash': string;
    /**
     * Index of the log within the transaction
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'logIndex': string;
    /**
     * Address of the token contract
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'contractAddress': string;
    /**
     * Address that sent the tokens
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'fromAddress': string;
    /**
     * Address that received the tokens
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'toAddress': string;
    /**
     * Amount of tokens transferred (in smallest unit)
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'value': string;
    /**
     * Chain ID of the blockchain
     * @type {number}
     * @memberof OnchainTransferEvent
     */
    'chainId': number;
    /**
     * The blockchain base asset identifier
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'baseAssetId': string;
    /**
     * Block number containing this transfer
     * @type {number}
     * @memberof OnchainTransferEvent
     */
    'blockNumber': number;
    /**
     * Hash of the block containing this transfer
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'blockHash': string;
    /**
     * Timestamp when the block was mined
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'blockTimestamp': string;
    /**
     * Name of the event (typically \"Transfer\")
     * @type {string}
     * @memberof OnchainTransferEvent
     */
    'eventName': string;
}

