/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccessType } from './access-type';
// May contain unused imports in some cases
// @ts-ignore
import { AccountReference } from './account-reference';
// May contain unused imports in some cases
// @ts-ignore
import { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import { SettlementSourceAccount } from './settlement-source-account';
// May contain unused imports in some cases
// @ts-ignore
import { Side } from './side';

/**
 * 
 * @export
 * @interface OrderSummary
 */
export interface OrderSummary {
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    'id': string;
    /**
     * 
     * @type {AccessType}
     * @memberof OrderSummary
     */
    'via': AccessType;
    /**
     * 
     * @type {Side}
     * @memberof OrderSummary
     */
    'side': Side;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    'baseAmount': string;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    'baseAssetId': string;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    'quoteAssetId': string;
    /**
     * 
     * @type {OrderStatus}
     * @memberof OrderSummary
     */
    'status': OrderStatus;
    /**
     * 
     * @type {AccountReference}
     * @memberof OrderSummary
     */
    'destination': AccountReference;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof OrderSummary
     */
    'quoteAmount'?: string;
    /**
     * 
     * @type {SettlementSourceAccount}
     * @memberof OrderSummary
     */
    'source'?: SettlementSourceAccount;
}



