/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Set of ids representing the users who signs transactions that match a specific rule
 * @export
 * @interface PolicyRuleDesignatedSigners
 */
export interface PolicyRuleDesignatedSigners {
    /**
     * Set of users ids
     * @type {Array<string>}
     * @memberof PolicyRuleDesignatedSigners
     */
    'users'?: Array<string>;
    /**
     * Set of group ids
     * @type {Array<string>}
     * @memberof PolicyRuleDesignatedSigners
     */
    'usersGroups'?: Array<string>;
}

