/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Operator for selection
 * @export
 * @enum {string}
 */

export const PolicyOperator = {
    Includes: 'INCLUDES'
} as const;

export type PolicyOperator = typeof PolicyOperator[keyof typeof PolicyOperator];



