/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuoteExecutionRequestDetails
 */
export interface QuoteExecutionRequestDetails {
    /**
     * Order type for quote orders
     * @type {string}
     * @memberof QuoteExecutionRequestDetails
     */
    'type': QuoteExecutionRequestDetailsTypeEnum;
    /**
     * Quote ID for quote orders
     * @type {string}
     * @memberof QuoteExecutionRequestDetails
     */
    'quoteId': string;
}

export const QuoteExecutionRequestDetailsTypeEnum = {
    Quote: 'QUOTE'
} as const;

export type QuoteExecutionRequestDetailsTypeEnum = typeof QuoteExecutionRequestDetailsTypeEnum[keyof typeof QuoteExecutionRequestDetailsTypeEnum];


