/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The status of the request
 * @export
 * @enum {string}
 */

export const RelatedRequestStatusType = {
    Error: 'error',
    Created: 'created',
    Canceled: 'canceled',
    ActivateRequested: 'activate_requested',
    ApproveInprogress: 'approve_inprogress',
    ApproveInprogressSigned: 'approve_inprogress_signed',
    ActivateInprogress: 'activate_inprogress',
    ActivateInprogressSigned: 'activate_inprogress_signed',
    ActivateInprogressConfirmed: 'activate_inprogress_confirmed',
    ActivateDone: 'activate_done',
    DeactivateRequested: 'deactivate_requested',
    DeactivateInprogress: 'deactivate_inprogress',
    DeactivateInprogressSigned: 'deactivate_inprogress_signed',
    DeactivateInprogressConfirmed: 'deactivate_inprogress_confirmed',
    DeactivateDone: 'deactivate_done',
    WithdrawInprogress: 'withdraw_inprogress',
    WithdrawRequested: 'withdraw_requested',
    WithdrawInprogressConfirmed: 'withdraw_inprogress_confirmed',
    WithdrawDone: 'withdraw_done',
    ClaimRewardsRequested: 'claim_rewards_requested',
    ClaimRewardsInprogress: 'claim_rewards_inprogress',
    ClaimRewardsDone: 'claim_rewards_done',
    Pending: 'pending',
    PendingQueued: 'pending_queued',
    ActiveOffline: 'active_offline',
    ActiveOnline: 'active_online',
    ExitingOnline: 'exiting_online',
    Exited: 'exited',
    Active: 'active',
    Inactive: 'inactive',
    Activating: 'activating',
    Deactivating: 'deactivating'
} as const;

export type RelatedRequestStatusType = typeof RelatedRequestStatusType[keyof typeof RelatedRequestStatusType];



