/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to reopen a FSPM finding.
 * @export
 * @interface ReopenFindingRequest
 */
export interface ReopenFindingRequest {
    /**
     * Marks the finding as open again.
     * @type {string}
     * @memberof ReopenFindingRequest
     */
    'status': ReopenFindingRequestStatusEnum;
    /**
     * Ignored when reopening a finding.
     * @type {string}
     * @memberof ReopenFindingRequest
     */
    'statusUpdatedReason'?: string;
}

export const ReopenFindingRequestStatusEnum = {
    Open: 'OPEN'
} as const;

export type ReopenFindingRequestStatusEnum = typeof ReopenFindingRequestStatusEnum[keyof typeof ReopenFindingRequestStatusEnum];


