/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RetryRequoteTypeEnum } from './retry-requote-type-enum';

/**
 * 
 * @export
 * @interface RetryRequoteRequestDetails
 */
export interface RetryRequoteRequestDetails {
    /**
     * 
     * @type {RetryRequoteTypeEnum}
     * @memberof RetryRequoteRequestDetails
     */
    'type': RetryRequoteTypeEnum;
    /**
     * If quote is expired, how many times to re-generate new quotes to try having the order executed as in the original quote.
     * @type {number}
     * @memberof RetryRequoteRequestDetails
     */
    'count': number;
    /**
     * Slippage tolerance in basis points (bps) for quote orders - 1 is 0.01% and 10000 is 100%
     * @type {number}
     * @memberof RetryRequoteRequestDetails
     */
    'slippageBps'?: number;
}



