/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RoleGrantee } from './role-grantee';

/**
 * 
 * @export
 * @interface RoleDetails
 */
export interface RoleDetails {
    /**
     * The role hash identifier
     * @type {string}
     * @memberof RoleDetails
     */
    'roleHash': string;
    /**
     * Human-readable description of the role
     * @type {string}
     * @memberof RoleDetails
     */
    'description': string;
    /**
     * List of accounts that have been granted this role
     * @type {Array<RoleGrantee>}
     * @memberof RoleDetails
     */
    'accounts': Array<RoleGrantee>;
}

