/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScreeningUpdateConfigurations
 */
export interface ScreeningUpdateConfigurations {
    /**
     * Flag to enable or disable bypass screening on tenant configuration.
     * @type {boolean}
     * @memberof ScreeningUpdateConfigurations
     */
    'disableBypass'?: boolean;
    /**
     * Flag to enable or disable unfreeze of transaction frozen by policy rule on tenant configuration.
     * @type {boolean}
     * @memberof ScreeningUpdateConfigurations
     */
    'disableUnfreeze'?: boolean;
}

