/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ScreeningTRLinkAmount } from './screening-trlink-amount';
// May contain unused imports in some cases
// @ts-ignore
import { ScreeningTRLinkRuleBase } from './screening-trlink-rule-base';
// May contain unused imports in some cases
// @ts-ignore
import { TRLinkMissingTrmActionEnum } from './trlink-missing-trm-action-enum';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionOperationEnum } from './transaction-operation-enum';
// May contain unused imports in some cases
// @ts-ignore
import { TransferPeerSubTypeEnum } from './transfer-peer-sub-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import { TransferPeerTypeEnum } from './transfer-peer-type-enum';
// May contain unused imports in some cases
// @ts-ignore
import { TravelRuleDirectionEnum } from './travel-rule-direction-enum';

/**
 * @type ScreeningTRLinkMissingTrmRule
 * TRLink missing TRM rule definition
 * @export
 */
export type ScreeningTRLinkMissingTrmRule = ScreeningTRLinkRuleBase;


