/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DvnConfig } from './dvn-config';

/**
 * 
 * @export
 * @interface SetLayerZeroDvnConfigRequest
 */
export interface SetLayerZeroDvnConfigRequest {
    /**
     * Vault account that pays gas
     * @type {string}
     * @memberof SetLayerZeroDvnConfigRequest
     */
    'vaultAccountId': string;
    /**
     * Source adapter TokenLink ID
     * @type {string}
     * @memberof SetLayerZeroDvnConfigRequest
     */
    'sourceAdapterTokenLinkId': string;
    /**
     * Destination adapter TokenLink ID
     * @type {string}
     * @memberof SetLayerZeroDvnConfigRequest
     */
    'destinationAdapterTokenLinkId': string;
    /**
     * 
     * @type {DvnConfig}
     * @memberof SetLayerZeroDvnConfigRequest
     */
    'sendConfig': DvnConfig;
    /**
     * 
     * @type {DvnConfig}
     * @memberof SetLayerZeroDvnConfigRequest
     */
    'receiveConfig': DvnConfig;
}

