/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SmartTransferCoinStatistic } from './smart-transfer-coin-statistic';

/**
 * Outflow tickets data
 * @export
 * @interface SmartTransferStatisticOutflow
 */
export interface SmartTransferStatisticOutflow {
    /**
     * 
     * @type {Array<SmartTransferCoinStatistic>}
     * @memberof SmartTransferStatisticOutflow
     */
    'coins'?: Array<SmartTransferCoinStatistic>;
    /**
     * 
     * @type {number}
     * @memberof SmartTransferStatisticOutflow
     */
    'ticketCount'?: number;
}

