/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SmartTransferApproveTerm
 */
export interface SmartTransferApproveTerm {
    /**
     * Asset name
     * @type {string}
     * @memberof SmartTransferApproveTerm
     */
    'asset': string;
    /**
     * Amount
     * @type {string}
     * @memberof SmartTransferApproveTerm
     */
    'amount': string;
    /**
     * Id of the vault that is used as the source of the asset.
     * @type {string}
     * @memberof SmartTransferApproveTerm
     */
    'srcId': string;
    /**
     * Transaction fee
     * @type {string}
     * @memberof SmartTransferApproveTerm
     */
    'fee'?: string;
    /**
     * Transaction fee level.
     * @type {string}
     * @memberof SmartTransferApproveTerm
     */
    'feeLevel'?: SmartTransferApproveTermFeeLevelEnum;
    /**
     * Transaction note
     * @type {string}
     * @memberof SmartTransferApproveTerm
     */
    'note'?: string;
}

export const SmartTransferApproveTermFeeLevelEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH'
} as const;

export type SmartTransferApproveTermFeeLevelEnum = typeof SmartTransferApproveTermFeeLevelEnum[keyof typeof SmartTransferApproveTermFeeLevelEnum];


