/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SmartTransferFundTermDto
 */
export interface SmartTransferFundTermDto {
    /**
     * Asset name
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'asset': string;
    /**
     * Amount
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'amount': string;
    /**
     * Id of the network connection used.
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'networkConnectionId': string;
    /**
     * Id of the vault that is used as the source of the asset.
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'srcId': string;
    /**
     * Source of the asset.
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'srcType': string;
    /**
     * Transaction fee
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'fee'?: string;
    /**
     * Transaction fee level.
     * @type {string}
     * @memberof SmartTransferFundTermDto
     */
    'feeLevel'?: string;
}

