/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SOLAccountWithValue } from './solaccount-with-value';
// May contain unused imports in some cases
// @ts-ignore
import { SolParameterWithValue } from './sol-parameter-with-value';

/**
 * 
 * @export
 * @interface SolanaInstructionWithValue
 */
export interface SolanaInstructionWithValue {
    /**
     * The name of the instruction
     * @type {string}
     * @memberof SolanaInstructionWithValue
     */
    'name': string;
    /**
     * The discriminator for the instruction. Acts as a function selector
     * @type {Array<number>}
     * @memberof SolanaInstructionWithValue
     */
    'discriminator': Array<number>;
    /**
     * 
     * @type {Array<SOLAccountWithValue>}
     * @memberof SolanaInstructionWithValue
     */
    'accounts': Array<SOLAccountWithValue>;
    /**
     * The arguments of the instruction
     * @type {Array<SolParameterWithValue>}
     * @memberof SolanaInstructionWithValue
     */
    'args': Array<SolParameterWithValue>;
}

