/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A breakdown of the staking rewards earned by the position.
 * @export
 * @interface SolanaRewardsBreakdown
 */
export interface SolanaRewardsBreakdown {
    /**
     * The issuance reward amount earned by the position, measured in the staked asset unit.
     * @type {string}
     * @memberof SolanaRewardsBreakdown
     */
    'issuance': string;
    /**
     * The MEV reward amount earned by the position, measured in the staked asset unit.
     * @type {string}
     * @memberof SolanaRewardsBreakdown
     */
    'mev': string;
    /**
     * The last time the rewards were synced (ISO Date).
     * @type {string}
     * @memberof SolanaRewardsBreakdown
     */
    'lastRewardSyncedAt': string;
}

