/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * The status of the command
     * @type {string}
     * @memberof Status
     */
    'status': StatusStatusEnum;
    /**
     * The type of the command
     * @type {string}
     * @memberof Status
     */
    'type': StatusTypeEnum;
}

export const StatusStatusEnum = {
    WaitingForApproval: 'WAITING_FOR_APPROVAL',
    Approved: 'APPROVED',
    Cancelled: 'CANCELLED',
    Rejected: 'REJECTED',
    Completed: 'COMPLETED'
} as const;

export type StatusStatusEnum = typeof StatusStatusEnum[keyof typeof StatusStatusEnum];
export const StatusTypeEnum = {
    PairApiKey: 'PAIR_API_KEY',
    UpdateCallbackHandler: 'UPDATE_CALLBACK_HANDLER',
    UnpairApiKey: 'UNPAIR_API_KEY'
} as const;

export type StatusTypeEnum = typeof StatusTypeEnum[keyof typeof StatusTypeEnum];


