/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'jobId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'tenantId'?: string;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'created'?: number;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'updated'?: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'state'?: string;
}

