/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The schedule for this deposit automation.
 * @export
 * @interface TimeBasedTrigger
 */
export interface TimeBasedTrigger {
    /**
     * How often the deposit runs, in units of intervalUnit.
     * @type {number}
     * @memberof TimeBasedTrigger
     */
    'intervalValue': number;
    /**
     * The unit for intervalValue.
     * @type {string}
     * @memberof TimeBasedTrigger
     */
    'intervalUnit': TimeBasedTriggerIntervalUnitEnum;
    /**
     * Minimum USDC balance required before a deposit runs. Set to \"0\" to sweep the full available balance every time, with no minimum.
     * @type {string}
     * @memberof TimeBasedTrigger
     */
    'balanceThreshold': string;
}

export const TimeBasedTriggerIntervalUnitEnum = {
    Minutes: 'MINUTES',
    Hours: 'HOURS',
    Days: 'DAYS'
} as const;

export type TimeBasedTriggerIntervalUnitEnum = typeof TimeBasedTriggerIntervalUnitEnum[keyof typeof TimeBasedTriggerIntervalUnitEnum];


