/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TokenLinkRequestDto
 */
export interface TokenLinkRequestDto {
    /**
     * The type of token being linked
     * @type {string}
     * @memberof TokenLinkRequestDto
     */
    'type': TokenLinkRequestDtoTypeEnum;
    /**
     * The Fireblocks\' token link reference id. For example, \'BQ5R_BDESC_ABC\' if it\'s a fungible       asset
     * @type {string}
     * @memberof TokenLinkRequestDto
     */
    'refId'?: string;
    /**
     * The token display name
     * @type {string}
     * @memberof TokenLinkRequestDto
     */
    'displayName'?: string;
    /**
     * The blockchain base assetId
     * @type {string}
     * @memberof TokenLinkRequestDto
     */
    'baseAssetId'?: string;
    /**
     * The contract\'s onchain address
     * @type {string}
     * @memberof TokenLinkRequestDto
     */
    'contractAddress'?: string;
}

export const TokenLinkRequestDtoTypeEnum = {
    FungibleToken: 'FUNGIBLE_TOKEN',
    NonFungibleToken: 'NON_FUNGIBLE_TOKEN',
    TokenUtility: 'TOKEN_UTILITY',
    TokenExtension: 'TOKEN_EXTENSION'
} as const;

export type TokenLinkRequestDtoTypeEnum = typeof TokenLinkRequestDtoTypeEnum[keyof typeof TokenLinkRequestDtoTypeEnum];


