/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TravelRulePersons } from './travel-rule-persons';

/**
 * 
 * @export
 * @interface TravelRulePiiIVMS
 */
export interface TravelRulePiiIVMS {
    /**
     * 
     * @type {Array<TravelRulePersons>}
     * @memberof TravelRulePiiIVMS
     */
    'originatorPersons'?: Array<TravelRulePersons>;
    /**
     * 
     * @type {Array<TravelRulePersons>}
     * @memberof TravelRulePiiIVMS
     */
    'beneficiaryPersons'?: Array<TravelRulePersons>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TravelRulePiiIVMS
     */
    'accountNumber'?: Array<string>;
}

