/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TravelRuleGeographicAddress } from './travel-rule-geographic-address';
// May contain unused imports in some cases
// @ts-ignore
import { TravelRuleLegalPersonNameIdentifier } from './travel-rule-legal-person-name-identifier';
// May contain unused imports in some cases
// @ts-ignore
import { TravelRuleNationalIdentification } from './travel-rule-national-identification';

/**
 * 
 * @export
 * @interface TravelRuleLegalPerson
 */
export interface TravelRuleLegalPerson {
    /**
     * 
     * @type {TravelRuleLegalPersonNameIdentifier}
     * @memberof TravelRuleLegalPerson
     */
    'name'?: TravelRuleLegalPersonNameIdentifier;
    /**
     * The array of geographic addresses associated with the legal person.
     * @type {Array<TravelRuleGeographicAddress>}
     * @memberof TravelRuleLegalPerson
     */
    'geographicAddress'?: Array<TravelRuleGeographicAddress>;
    /**
     * 
     * @type {TravelRuleNationalIdentification}
     * @memberof TravelRuleLegalPerson
     */
    'nationalIdentification'?: TravelRuleNationalIdentification;
    /**
     * A unique identifier that identifies the customer in the organization\'s context. The value must be encrypted.
     * @type {string}
     * @memberof TravelRuleLegalPerson
     */
    'customerIdentification'?: string;
    /**
     * A distinct identifier that uniquely identifies the customer within the organization. The value must be encrypted.
     * @type {string}
     * @memberof TravelRuleLegalPerson
     */
    'customerNumber'?: string;
    /**
     * The ISO-3166 Alpha-2 country code where the legal person is registered. The value must be encrypted.
     * @type {string}
     * @memberof TravelRuleLegalPerson
     */
    'countryOfRegistration'?: string;
}

