/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents the date and place of birth for a natural person
 * @export
 * @interface TravelRuleValidateDateAndPlaceOfBirth
 */
export interface TravelRuleValidateDateAndPlaceOfBirth {
    /**
     * Date of birth in ISO 8601 format (YYYY-MM-DD)
     * @type {string}
     * @memberof TravelRuleValidateDateAndPlaceOfBirth
     */
    'dateOfBirth'?: string;
    /**
     * Place of birth
     * @type {string}
     * @memberof TravelRuleValidateDateAndPlaceOfBirth
     */
    'placeOfBirth'?: string;
}

