/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IVMS101 data structure containing encrypted PII
 * @export
 * @interface TRLinkIvms
 */
export interface TRLinkIvms {
    /**
     * IVMS version
     * @type {string}
     * @memberof TRLinkIvms
     */
    'version': string;
    /**
     * Encrypted IVMS101 data containing originator and beneficiary information
     * @type {string}
     * @memberof TRLinkIvms
     */
    'data': string;
    /**
     * List of fields that are filled in the IVMS data
     * @type {Array<string>}
     * @memberof TRLinkIvms
     */
    'filledFields': Array<string>;
}

