/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: developers@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WebhookOauthCustomBodyParamsUpdate } from './webhook-oauth-custom-body-params-update';
// May contain unused imports in some cases
// @ts-ignore
import { WebhookOauthCustomHeadersUpdate } from './webhook-oauth-custom-headers-update';
// May contain unused imports in some cases
// @ts-ignore
import { WebhookOauthCustomJwtClaimsUpdate } from './webhook-oauth-custom-jwt-claims-update';

/**
 * A partial update. Every field is optional and an omitted field is left as it is, so `{ \"clientSecret\": \"new-secret\" }` rotates the secret and changes nothing else. A rotation applies to every webhook referencing these credentials.  The three custom maps merge. A key with a value is upserted, a key with `null` is deleted, a key you leave out is untouched, and the whole field set to `null` clears the map. There is no ambiguity between the two uses of `null` — one names an entry, the other names the field. `mtlsClientSignedCert` is a scalar, so `null` there removes it.
 * @export
 * @interface UpdateWebhookOauthRequest
 */
export interface UpdateWebhookOauthRequest {
    /**
     * A label for this credential set. Omit to leave it unchanged.
     * @type {string}
     * @memberof UpdateWebhookOauthRequest
     */
    'name'?: string;
    /**
     * OAuth client ID. Omit to leave it unchanged.
     * @type {string}
     * @memberof UpdateWebhookOauthRequest
     */
    'clientId'?: string;
    /**
     * A new OAuth client secret. Limited to 480 bytes when UTF-8 encoded, so a secret using non-ASCII characters fits fewer than 480 of them. Write-only — never returned in any response. Send this on its own to rotate the secret without changing anything else. Omit to leave it unchanged.
     * @type {string}
     * @memberof UpdateWebhookOauthRequest
     */
    'clientSecret'?: string;
    /**
     * Token endpoint URL. HTTPS on port 443 only, and the host must resolve publicly. Omit to leave it unchanged.
     * @type {string}
     * @memberof UpdateWebhookOauthRequest
     */
    'url'?: string;
    /**
     * `client_secret_basic`, `client_secret_post` or `client_secret_jwt`. Omit to leave it unchanged — it does not revert to the default.
     * @type {string}
     * @memberof UpdateWebhookOauthRequest
     */
    'authMethod'?: string;
    /**
     * 
     * @type {WebhookOauthCustomJwtClaimsUpdate}
     * @memberof UpdateWebhookOauthRequest
     */
    'customJwtClaims'?: WebhookOauthCustomJwtClaimsUpdate | null;
    /**
     * 
     * @type {WebhookOauthCustomBodyParamsUpdate}
     * @memberof UpdateWebhookOauthRequest
     */
    'customBodyParams'?: WebhookOauthCustomBodyParamsUpdate | null;
    /**
     * 
     * @type {WebhookOauthCustomHeadersUpdate}
     * @memberof UpdateWebhookOauthRequest
     */
    'customHeaders'?: WebhookOauthCustomHeadersUpdate | null;
    /**
     * PEM-encoded client certificate for mTLS. Must be a valid X.509 certificate inside its validity window. Omit to leave it unchanged, or send `null` to remove it.
     * @type {string}
     * @memberof UpdateWebhookOauthRequest
     */
    'mtlsClientSignedCert'?: string | null;
}

