/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The status of the user
 * @export
 * @enum {string}
 */

export const UserStatus = {
    PendingActivation: 'PENDING_ACTIVATION',
    PendingDevicePairing: 'PENDING_DEVICE_PAIRING',
    PendingDeviceSetup: 'PENDING_DEVICE_SETUP',
    Ready: 'READY'
} as const;

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];



