/* tslint:disable */
/* eslint-disable */
/**
 * Fireblocks API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.2
 * Contact: support@fireblocks.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { XBSettlementAsset } from './xbsettlement-asset';

/**
 * 
 * @export
 * @interface XBSettlementFlowSetupStep
 */
export interface XBSettlementFlowSetupStep {
    /**
     * 
     * @type {string}
     * @memberof XBSettlementFlowSetupStep
     */
    'accountId': string;
    /**
     * 
     * @type {XBSettlementAsset}
     * @memberof XBSettlementFlowSetupStep
     */
    'inputAmount': XBSettlementAsset;
    /**
     * 
     * @type {XBSettlementAsset}
     * @memberof XBSettlementFlowSetupStep
     */
    'outputAmount': XBSettlementAsset;
    /**
     * 
     * @type {XBSettlementAsset}
     * @memberof XBSettlementFlowSetupStep
     */
    'estimatedFeeAmount': XBSettlementAsset;
    /**
     * The estimated time for executing the step.
     * @type {number}
     * @memberof XBSettlementFlowSetupStep
     */
    'estimatedTime': number;
    /**
     * Whether or not signing is required for executing the step.
     * @type {boolean}
     * @memberof XBSettlementFlowSetupStep
     */
    'isSignRequired': boolean;
}

